---
- name: Ensure /etc/samba/smb.conf
  copy: >
    src=smb.conf
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    mode=0644
  notify:
    - Restart SSSD

- name: Ensure /etc/sssd/sssd.conf
  template: >
    src=sssd.j2
    dest=/etc/sssd/sssd.conf
    owner=root
    group=root
    mode=0600
  notify:
    - Restart SSSD

- name: Ensure /etc/krb5.conf
  copy: >
    src=krb5.conf
    dest=/etc/krb5.conf
    owner=root
    group=root
    mode=0644
  notify:
    - Restart SSSD

- name: Restart SSSD
  service: >
    name=sssd
    state=restarted

- name: Ensure Winbind disabled
  service: >
    name=winbind
    enabled=no
    state=stopped
  failed_when: false
