---
- name: Ensure SSSD RPMs
  yum:
    name=adcli,sssd,krb5-workstation,samba-common
    state=present

- name: Ensure /etc/samba/smb.conf
  copy:
    src=smb.conf
    dest=/etc/samba/smb.conf
    owner=root
    group=root
    mode=0644

- name: Ensure /etc/sssd/sssd.conf
  template:
    src=sssd.j2
    dest=/etc/sssd/sssd.conf
    owner=root
    group=root
    mode=0600
  notify:
    - Restart SSSD

- name: Ensure /etc/krb5.conf
  copy:
    src=krb5.conf
    dest=/etc/krb5.conf
    owner=root
    group=root
    mode=0644

- name: Ensure Winbind disabled
  service:
    name=winbind
    enabled=no
    state=stopped
  failed_when: false

- name: Check AD status
  shell: /usr/sbin/sss_cache -u _svc_machine_add > /dev/null 2>&1; /usr/bin/id _svc_machine_add | /bin/grep "no such user"
  register: ad_status
  changed_when: false
  failed_when: false

- name: SSSD Authconfig
  shell: /usr/sbin/authconfig --enablesssd --enablesssdauth --enablemkhomedir --enablepamaccess --disablewinbind --disablewinbindauth  --updateall
  when: ad_status.stderr != '' or reauth is defined
  notify:
    - Ensure /etc/samba/smb.conf
    - Ensure /etc/sssd/sssd.conf
    - Ensure /etc/krb5.conf
    - Ensure Winbind disabled

- name: Join AD Domain
  shell: /usr/bin/net ads join -U {{ AD_USER }}%{{ AD_PASS }} createcomputer="Resources/Servers/Linux_Server"
  changed_when: false
  when: ad_status.stderr != '' or reauth is defined
  notify:
    - Ensure /etc/samba/smb.conf
    - Ensure /etc/sssd/sssd.conf
    - Ensure /etc/krb5.conf
    - Ensure Winbind disabled

- name: Check for keytab
  stat: 
    path=/etc/krb5.keytab
  register: ktab
  changed_when: false

- name: Create keytab
  shell: net ads keytab create
  when: ktab.stat.exists == False or reauth is defined
  notify:
    - Ensure /etc/samba/smb.conf
    - Ensure /etc/sssd/sssd.conf
    - Ensure /etc/krb5.conf
    - Ensure Winbind disabled
    - Restart SSSD

- meta: flush_handlers

- name: Ensure SSSD service
  service: 
    name=sssd
    enabled=yes
    state=started

- name: Ensure pam_access listsep
  replace: 
    dest=/etc/pam.d/{{ item }}
    regexp='pam_access.so$'
    replace="pam_access.so listsep=,"
  with_items:
    - atd
    - crond
    - fingerprint-auth
    - password-auth
    - smartcard-auth
    - system-auth

- name: Ensure pam_tally
  lineinfile: 
    dest=/etc/pam.d/system-auth-ac
    state=present
    line="auth        required      pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900"
    insertafter="auth        sufficient    pam_unix.so try_first_pass"

- name: Ensure PAM passsword history
  replace: 
    dest=/etc/pam.d/system-auth-ac
    regexp='pam_unix.so sha512 shadow try_first_pass use_authtok$'
    replace="pam_unix.so sha512 shadow try_first_pass use_authtok remember=5"

- name: Ensure PAM password minlen=14
  replace: 
    dest=/etc/pam.d/system-auth-ac
    regexp='minlen=8'
    replace="minlen=14"

- name: Ensure nsswitch.conf settings
  lineinfile: 
    dest=/etc/nsswitch.conf
    regexp="^{{ item }}:"
    line="{{ item }}:         files sss"
  with_items:
    - passwd
    - shadow
    - group
    - automount
    - netgroup

